---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-rclone
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: fedora28
    - MOLECULE_DISTRO: fedora28
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: fedora26
    - MOLECULE_DISTRO: fedora25
    - MOLECULE_DISTRO: ubuntu1810
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  #- cd ../
  #- mv ansible-role-$ROLE_NAME stefangweichinger.$ROLE_NAME
  #- cd stefangweichinger.$ROLE_NAME

script:
  # Run tests.
  - molecule test

#notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
