---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-rclone
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora32
    - MOLECULE_DISTRO: fedora31
    - MOLECULE_DISTRO: fedora30
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule==3.0.6 docker==4.2.2 yamllint ansible-lint

script:
  - molecule --version
  - ansible --version
  # Run tests.
  - molecule test -s travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
