---

name: Molecule

on:
  push:
    branches:
      - master
      - ci_*
  pull_request:
    branches:
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - travis
        distros:
          - geerlingguy/docker-centos7-ansible
          - geerlingguy/docker-centos8-ansible
          - geerlingguy/docker-ubuntu2004-ansible
          - geerlingguy/docker-ubuntu1804-ansible
          - geerlingguy/docker-ubuntu1604-ansible
          - geerlingguy/docker-debian10-ansible
          - geerlingguy/docker-debian9-ansible
          - geerlingguy/docker-fedora32-ansible
          - geerlingguy/docker-fedora31-ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
        with:
          # molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_options: --debug
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
